name: Deployment Workflow
on:
   push:
     branches: [ master ]
     
jobs:
  first_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
    - name: testing ssh connection
      uses: BogdanGrekk/ssh-action@master
      with:
        host: ftpupload.net
        username:	epiz_30815335
        key: ${{ aAtTXrkPxWuAnw4 }}
        port: 21
        script: |
         cd website
         git pull origin master 
         git status
    

